### ISSUE TITLE
audio is recorded but cuts out intermittedly

### ISSUE THREAD

**Issue by mistmist** [SeaDve/Kooha#106]
having a weird problem here:
any recording of audio from the microphone will go on-and-off-and-on-and-off once a second here, it's not usable.

have build libadwaita and Kooha from git master yesterday, on up-to-date Fedora 34/Gnome 40.

the funny thing is that yesterday this didn't happen, but today it does, even in the shortest of recordings.

3 other applications record audio without this problem: Sound Recorder, Audacity and OBS Studio.

but it's quite possible this is a bug in some lower-level component.

**Comment by SeaDve** [comment]
hi, can you show the logs with the following environment variables reproducing the error: `GST_DEBUG=3 PIPEWIRE_DEBUG=3 RUST_LOG=kooha=debug`

**Comment by mistmist** [comment]
hmm... i suspect the problem is "Dropped 24960 samples. This is most likely because downstream can't keep up and is consuming samples too slowly."


 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 1.2.1 ()
 INFO  kooha::application > Datadir: /home/ms/stuff/install/share/kooha
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 INFO  kooha::backend::screencast_portal > Session created
 INFO  kooha::backend::screencast_portal > Select sources window showed
 INFO  kooha::backend::screencast_portal > Screencast session started
 INFO  kooha::backend::screencast_portal > Ready for pipewire stream
 DEBUG kooha::backend::recorder          > pulse_server_version: PulseAudio (on PipeWire 0.3.34) version 15.0.0
 DEBUG kooha::backend::recorder          > PipelineBuilder { is_record_speaker: false, is_record_mic: true, framerate: 30, file_path: "/home/ms/Videos/Kooha 09-09-2021 11:35:24.webm", fd: 22, streams: [Stream { pipewire_node_id: 74, position: Some((1920, 0)), size: Some((1920, 1200)) }], speaker_source: Some("alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"), mic_source: Some("alsa_input.pci-0000_00_1f.3.analog-stereo"), coordinates: None, actual_screen: None }
 DEBUG kooha::backend::pipeline_builder  > is_use_vaapi: false
 DEBUG kooha::backend::pipeline_builder  > pipeline_string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=8 ! queue ! vp8enc max_quantizer=17 cpu-used=16 cq_level=13 deadline=1 static-threshold=100 keyframe-mode=disabled buffer-size=20000 threads=8 ! queue ! webmmux name=mux ! filesink name=filesink location="/home/ms/Videos/Kooha 09-09-2021 11:35:24.webm" pipewiresrc fd=22 path=74 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw, max-framerate=30/1 ! queue0. pulsesrc device="alsa_input.pci-0000_00_1f.3.analog-stereo" ! opusenc ! queue ! mux.
[I][20840.696977][      pipewire.c:  562 pw_init()] version 0.3.34
[I][20840.704288][          conf.c:  326 conf_load()] config 0x558cde925f90: loading config '/usr/share/pipewire/client.conf'
[I][20840.704365][       context.c:  348 pw_context_new()] context 0x558cdd6b5400: parsed context.properties section
[I][20840.704752][       context.c:  438 pw_context_new()] context 0x558cdd6b5400: parsed 2 context.spa-libs items
[I][20840.705122][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-protocol-native
[I][20840.705509][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-client-node
[I][20840.705770][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-client-device
[I][20840.706039][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-adapter
[I][20840.706287][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-metadata
[I][20840.706570][          conf.c:  419 load_module()] config 0x558cdd6b5400: loaded module libpipewire-module-session-manager
[I][20840.706589][       context.c:  442 pw_context_new()] context 0x558cdd6b5400: parsed 6 context.modules items
[I][20840.706602][       context.c:  447 pw_context_new()] context 0x558cdd6b5400: parsed 0 context.objects items
[I][20840.706611][       context.c:  450 pw_context_new()] context 0x558cdd6b5400: parsed 0 context.exec items
[I][20840.706659][       context.c:  241 context_set_freewheel()] context 0x558cdd6b5400: exit freewheel
[I][20840.706678][       context.c:  245 context_set_freewheel()] context 0x558cdd6b5400: freewheel error:Operation not supported
[I][20840.706694][ impl-metadata.c:  196 impl_set_property()] metadata 0x558cdea4f890: add id:0 key:log.level type: value:0
[I][20840.706704][ impl-metadata.c:  196 impl_set_property()] metadata 0x558cdea4f890: add id:0 key:clock.min-quantum type: value:32
[I][20840.706712][ impl-metadata.c:  196 impl_set_property()] metadata 0x558cdea4f890: add id:0 key:clock.max-quantum type: value:8192
[I][20840.706723][ impl-metadata.c:  196 impl_set_property()] metadata 0x558cdea4f890: add id:0 key:clock.force-quantum type: value:0
[I][20840.706731][ impl-metadata.c:  196 impl_set_property()] metadata 0x558cdea4f890: add id:0 key:clock.force-rate type: value:0
0:00:15.110405034 [35m39928[00m 0x7f727007b980 [32;01mFIXME  [00m [00;04m             default gstutils.c:4025:gst_pad_create_stream_id_internal:<pulsesrc0:src>[00m Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:15.110529968 [35m39928[00m 0x7f727008fa40 [32;01mFIXME  [00m [00;04m             default gstutils.c:4025:gst_pad_create_stream_id_internal:<pipewiresrc0:src>[00m Creating random stream-id, consider implementing a deterministic way of creating a stream-id
[I][20840.850796][     impl-node.c:  356 node_update_state()] (kooha-0) creating -> running
 INFO  kooha::backend::recorder          > Pipeline state set from Null -> Ready
 INFO  kooha::backend::recorder          > Pipeline state set from Ready -> Paused
0:00:15.369488123 [35m39928[00m 0x7f7270078180 [32;01mFIXME  [00m [00m            basesink gstbasesink.c:3384:gst_base_sink_default_event:<filesink>[00m stream-start event without group-id. Consider implementing group-id handling in the upstream elements
 INFO  kooha::backend::recorder          > Pipeline state set from Paused -> Playing
0:00:17.853310655 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:838:gst_audio_base_src_create:<pulsesrc0>[00m create DISCONT of 16800 samples at sample 125280
0:00:17.853332909 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Can't record audio fast enough
0:00:17.853337692 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Dropped 16800 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.
0:00:22.839778168 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:838:gst_audio_base_src_create:<pulsesrc0>[00m create DISCONT of 21600 samples at sample 364800
0:00:22.839808248 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Can't record audio fast enough
0:00:22.839815630 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Dropped 21600 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.
0:00:25.842258701 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:838:gst_audio_base_src_create:<pulsesrc0>[00m create DISCONT of 24960 samples at sample 508800
0:00:25.842288355 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Can't record audio fast enough
0:00:25.842295532 [35m39928[00m 0x7f727007b980 [33;01mWARN   [00m [00m        audiobasesrc gstaudiobasesrc.c:841:gst_audio_base_src_create:<pulsesrc0>[00m warning: Dropped 24960 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.
 INFO  kooha::backend::recorder          > Sending eos event to pipeline
0:00:27.524648399 [35m39928[00m 0x7f727007c180 [33;01mWARN   [00m [00m            audiosrc gstaudiosrc.c:227:audioringbuffer_thread_func:<pulsesrc0>[00m error reading data -1 (reason: Resource temporarily unavailable), skipping segment
[I][20853.121976][     impl-node.c:  356 node_update_state()] (kooha-0) running -> idle
[I][20853.129504][     impl-node.c:  356 node_update_state()] (kooha-0) idle -> suspended
[I][20853.129559][     impl-node.c: 1721 pw_impl_node_destroy()] (kooha-0) destroy
 INFO  kooha::backend::screencast_portal > Session closed
 INFO  kooha::backend::recorder          > Eos signal received from record bus

**Comment by SeaDve** [comment]
I think you're right, the audio encoder can't keepup, so certain hardware may struggle.

 i think the easy solution to this is vastly reduce the bitrate, since what kooha currently have is probably overkill. The other solution is adjust the speed of audio encoder in accordance to situation

**Comment by SeaDve** [comment]
The line determining this is in https://github.com/SeaDve/Kooha/blob/5d6d08e72befec18620dd1dd8239adc0a6de55d6/src/backend/pipeline_builder.rs#L293

You can play with the settings by replacing `opusenc` with something like `opusenc bitrate=10000` or something (the default is 64000.

**Comment by mistmist** [comment]
tried that, didn't help; switching to "vorbisenc", same problem; switching video to mp4, same problem

**Comment by SeaDve** [comment]
I'll investigate on it again in time. For now, ill leave the issue open, and thanks for the logs and testing!

**Comment by retromuz** [comment]
I face a similar issue however not same. My issue is with recorded sound from output of a program (eg Youtube).

See below logs. These logs appear only when the recorded screen does change what is rendered. Whenever I have a movie playing / have htop running at higher refresh rates, everything is good. Whenever there is less activity, recorded sound is broken.

`0:03:25.451245139 24268 0x7f1a80115360 WARN            audiobasesrc gstaudiobasesrc.c:843:gst_audio_base_src_create:<pulsesrc0> create DISCONT of 27360 samples at sample 9417600
0:03:25.451424914 24268 0x7f1a80115360 WARN            audiobasesrc gstaudiobasesrc.c:846:gst_audio_base_src_create:<pulsesrc0> warning: Can't record audio fast enough
0:03:25.451452572 24268 0x7f1a80115360 WARN            audiobasesrc gstaudiobasesrc.c:846:gst_audio_base_src_create:<pulsesrc0> warning: Dropped 27360 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.`

**Comment by maymage** [comment]
@SeaDve 

First thanks of course for this great app! Unfortunately, when trying to record a seminar presentation of mine, I've lost the audio due to this bug. Evidently I was too enthusiastic and didn't check kooha's functionality beforehand thoroughly.

Until this is fixed, you may wish to put a warning on the flathub site, so that this doesn't happen to others as well - I mean, well, this bug compromises primary functionality.

**Comment by carlhoerberg** [comment]
Starting `kooha` with `nice -20` fixed the choppy sound issues for me.

**Comment by stronnag** [comment]
`Some("opusenc bitrate=16000")` fixed this for me (and the associated "late video" in vlc), old "Haswell" I7.

**Comment by somepaulo** [comment]
> `Some("opusenc bitrate=16000")` fixed this for me (and the associated "late video" in vlc), old "Haswell" I7.

Where do you set this?

**Comment by stronnag** [comment]
> > Starting `kooha` with `nice -20` fixed the choppy sound issues for me.
> 
> Doesn't work for me (Core i5-6267U).
> 
> > `Some("opusenc bitrate=16000")` fixed this for me (and the associated "late video" in vlc), old "Haswell" I7.
> 
> Where do you set this?

```
$ git diff
diff --git a/src/backend/pipeline_builder.rs b/src/backend/pipeline_builder.rs
index 58edb2c..b5f52a6 100644
--- a/src/backend/pipeline_builder.rs
+++ b/src/backend/pipeline_builder.rs
@@ -282,7 +282,9 @@ impl PipelineAssembler {
 
     fn audioenc(&self) -> Option<String> {
         match self.video_format() {
-            VideoFormat::Webm | VideoFormat::Mkv | VideoFormat::Mp4 => Some("opusenc"),
+            VideoFormat::Webm | VideoFormat::Mkv | VideoFormat::Mp4 => {
+                Some("opusenc bitrate=16000")
+            }
             VideoFormat::Gif => None,
         }
         .map(str::to_string)
```
just an ugly hack to see if it helped.

**Comment by SeaDve** [comment]
This is likely fixed on the `encodebin-lite` branch

**Comment by SeaDve** [comment]
Fixed should be released on `2.2.0`.

**Comment by vijay-prema** [comment]
I am still seeing this issue on v2.2.3.  Tried turning on `KOOHA_EXPERIMENTAL=1 GST_VAAPI_ALL_DRIVERS=1` and it still didnt help.

**Comment by ruanformigoni** [comment]
I also have this issue, on archlinux version `2.2.3`.

**Comment by mefistotelis** [comment]
Happens to me as well, audio works, then starts stuttering and goes out completely, then comes back stuttering at first until it gets fully on.

I suspect the games can just consume any amount of CPU. So the fix should be an option to boost priority of encoding processes.

**Comment by SeaDve** [comment]
Closing this as duplicate of https://github.com/SeaDve/Kooha/issues/218

**Comment by SeaDve** [comment]
This is fixed now on the main branch.

**Comment by SeaDve** [comment]
I have published a patch on Flathub that should be available on `flatpak update` any time now.
